name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "chore(release):*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Clean install dependencies
        run: npm ci

      - name: Set Git user
        run: |
          git config user.email "subratpatnaik.email@gmail.com"
          git config user.name "Subrat Kumar Pattanaik"

      - name: Create release
        run: npm run release

      - name: Push changes and tags
        run: git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure npm for authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
